const bounties = [
  { id: 'V-0421', status: 'open', sector: 'CLIMATE', title: 'Prove that the Riau canopy restoration crossed 500 hectares.', team: 'Earthline / 4 sources required', reward: '2,400', people: ['E', 'L', 'J'] },
  { id: 'V-0419', status: 'verifying', sector: 'OPEN SOURCE', title: 'Confirm this dependency has no critical vulnerability.', team: 'Aperture Labs / verification in progress', reward: '850', people: ['A', 'M'] },
  { id: 'V-0414', status: 'open', sector: 'PUBLIC GOOD', title: 'Show that 10,000 households received clean water access.', team: 'Clearwell / 3 sources required', reward: '1,800', people: ['C', 'R', 'N'] },
  { id: 'V-0408', status: 'final', sector: 'GOVERNANCE', title: 'Verify the city published its complete procurement data.', team: 'Open Ward / settled 2 hours ago', reward: '600', people: ['O', 'W'] },
  { id: 'V-0402', status: 'verifying', sector: 'RESEARCH', title: 'Validate the public benchmark reproduces reported results.', team: 'Lab Note / 5 validators reading', reward: '1,050', people: ['L', 'S', 'P'] },
  { id: 'V-0398', status: 'open', sector: 'PRODUCT', title: 'Prove the accessibility release meets WCAG AA.', team: 'Kindred / 2 sources required', reward: '720', people: ['K', 'T'] }
];
const cards = document.querySelector('#cards'); const search = document.querySelector('#search'); let current = 'all';
function render() { const q = search.value.toLowerCase(); cards.innerHTML = bounties.filter(x => (current === 'all' || x.status === current) && `${x.title} ${x.sector} ${x.team}`.toLowerCase().includes(q)).map(x => `<article class="card"><div class="card-top"><span>${x.id} · ${x.sector}</span><span class="tag ${x.status}">${x.status === 'open' ? 'OPEN' : x.status === 'verifying' ? 'VERIFYING' : 'FINAL'}</span></div><h3>${x.title}</h3><p>${x.team}</p><div class="card-bottom"><div class="reward">${x.reward} <small>GEN</small></div><div class="avatars">${x.people.map(p=>`<i>${p}</i>`).join('')}</div></div></article>`).join(''); }
search.addEventListener('input', render); document.querySelector('#tabs').addEventListener('click', e => { if (!e.target.dataset.filter) return; current = e.target.dataset.filter; document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('selected', x === e.target)); render(); }); render();
const dialog = document.querySelector('#createDialog'); document.querySelector('#openCreate').onclick = () => dialog.showModal(); document.querySelector('#scrollDiscover').onclick = () => document.querySelector('#discover').scrollIntoView(); document.querySelector('#createBounty').onclick = e => { e.preventDefault(); dialog.close(); const toast = document.querySelector('#toast'); toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'), 3400); }; document.addEventListener('keydown', e => { if(e.key === 'Escape') dialog.close(); });
document.querySelectorAll('.brand').forEach(brand => { brand.lastChild.textContent = 'PROOFLOOM'; });
const revealObserver = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('is-visible'); }), { threshold: .15 });
document.querySelectorAll('.card, .steps article, .proof-copy, .ledger').forEach((el, i) => { el.style.setProperty('--delay', `${i * 70}ms`); revealObserver.observe(el); });
window.addEventListener('pointermove', event => { document.documentElement.style.setProperty('--mx', `${event.clientX / window.innerWidth * 100}%`); document.documentElement.style.setProperty('--my', `${event.clientY / window.innerHeight * 100}%`); });
